name: Build and Test

on:
  workflow_call: 
    inputs:
      branch:
        description: 'Branch name that this workflow will run'
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Print branch name
      run: echo Running build and test for branch ${{ inputs.branch }}
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'oracle'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.8.0
      with:
        gradle-version: 8.1.1
    - name: Execute Gradle Build
      run: ./gradlew build
    - name: Upload artifact build
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build