name: Build and Test Developer branch
on:
    push: 
        branches: [ "developer" ]
    pull_request: 
        branches: [ "developer" ]

jobs:
    build-and-test:
        name: "Build and Test Developer branch"
        uses: ./.github/workflows/build-test.yml
        with:
            branch: "developer"