name: Build and Test

on:
  push:
    branches: [ "developer" ]
  pull_request:
    branches: [ "developer" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'oracle'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.8.0
      with:
        gradle-version: 8.1.1
    - name: Execute Gradle Build
      run: ./gradlew build